### ISSUE TITLE
Pushbin fails with TargetList

### ISSUE THREAD

**Issue by Franky4fngers** [davehull/Kansa#146] opened 2016-01-22 15:45 UTC
Tried hostnames and IP addresses.  When the pushbin option is used in a targetlist it fails with the following error.  

Cannot process argument transformation on parameter 'Destination'. Cannot convert value to type System.String.

**Comment by EverythingTxyz** [comment] 2016-03-09 21:02
I have the same issue

**Comment by z4ns4tsu** [comment] 2016-04-22 17:20
Do you have any other errors in the error.log file for that run about the session not being created correctly?

Which module are you calling and what binary are you trying to push?

I'm going to guess that you're also not seeing a verbose message like "Starting WinRM copy of [file] to [place]:?

**Comment by Franky4fngers** [comment] 2016-04-27 20:09
I will try and get more information as soon as I can.  

My initial reports were hastier than desired. 

Thank You

**Comment by Franky4fngers** [comment] 2016-04-28 13:45
The relevant error is:

Cannot process argument transformation on parameter 'Destination'. Cannot convert value to type System.String.

If I run anything with a pushbin flag it fails with a targetlist.  I am currently using autorunsc in this case.  It has also failed with the others I have tested (as expected with this error)  The script works fine when run against an individual host.  

PS C:\Kansa-master> .\kansa.ps1 -TargetList .\testlist9.txt -ModulePath .\Modules -Pushbin -Debug
DEBUG: Sanity checking parameters
DEBUG: Parameter sanity check complete.
DEBUG: Entering Set-KansaPath
DEBUG: Exiting Set-KansaPath
DEBUG: $ModulePath is .\Modules.
DEBUG: $OutputPath is C:\Kansa-master\Output_20160428083950\.
DEBUG: $ServerList is .\testlist9.txt.
DEBUG: Entering Get-Modules
DEBUG: $ModulePath is .\Modules.
VERBOSE: Found .\Modules\Modules.conf.
VERBOSE: Running modules:
Get-Autorunsc
DEBUG: Exiting Get-Modules
DEBUG: Entering Get-Targets
VERBOSE: $Targets are <removed> 
DEBUG: Entering Get-TargetData
DEBUG: Entering Get-Directives
Caught: Cannot process argument transformation on parameter 'Destination'. Cannot convert value to type System.String.
Script completed with warnings or errors. See C:\Kansa-master\Output_20160428083950\Error.Log for details.

Thank You

**Comment by z4ns4tsu** [comment] 2016-04-28 15:48
That looks like it's not parsing your target list correctly. It should list out the entries in the testlist9.txt file on the "VERBOSE: $Targets are" line. Let me see if I can identify a problem in the code, but can you verify that file contains one host name or IP address per line? Also, is it ASCII or Unicode encoded?

**Comment by z4ns4tsu** [comment] 2016-04-28 16:23
I wasn't able to find anything that would cause this problem by walking the code paths involved, and it's strange it only happens when you've set the -Pushbin flag as that doesn't change how $Targets is built or used.  Can you try typing these lines in a console and pasting back the output (redact sensitive info as necessary, please):

```PowerShell
Set-Location C:\Kansa-master
$TargetList = '.\testlist9.txt'
Get-ChildItem $TargetList | Format-List -Property *
$Targets = Get-Content $TargetList | Foreach-Object { $_.Trim() } | Where-Object { $_.Length -gt 0 }
$Targets.Count
Write-Output "`$Targets are ${Targets}"
```

**Comment by z4ns4tsu** [comment] 2016-04-28 21:09
So I found what code is throwing that error, and it's in a path that's only traversed if -Pushbin is called. There's some better error handling we can do there, and I'll get that checked in soon, but I still don't think it's the root of the problem. All the error handling will do is make it more clear when the path failed, but I think it's still related to the $Targets variable not getting populated.

**Comment by Franky4fngers** [comment] 2016-05-02 15:22
I can verify the list is one host per line and ANSI.  It doesn't seem to matter of I run it on two or 100.  I tried several variations.  IP addresses only, hostnames, full qualified DNS names etc.  The hostnames are somewhat random character asset tag style names.  

> 

PS C:\Kansa-master> Set-Location C:\Kansa-master
PS C:\Kansa-master> $TargetList = '.\testlist9.txt'
PS C:\Kansa-master> Get-ChildItem $TargetList | Format-List -Property *
PSPath            : Microsoft.PowerShell.Core\FileSystem::C:\Kansa-master\testl
                    ist9.txt
PSParentPath      : Microsoft.PowerShell.Core\FileSystem::C:\Kansa-master
PSChildName       : testlist9.txt
PSDrive           : C
PSProvider        : Microsoft.PowerShell.Core\FileSystem
PSIsContainer     : False
VersionInfo       : File:             C:\Kansa-master\testlist9.txt
                    InternalName:
                    OriginalFilename:
                    FileVersion:
                    FileDescription:
                    Product:
                    ProductVersion:
                    Debug:            False
                    Patched:          False
                    PreRelease:       False
                    PrivateBuild:     False
                    SpecialBuild:     False
                    Language:

BaseName          : testlist9
Mode              : -a---
Name              : testlist9.txt
Length            : 1107
DirectoryName     : C:\Kansa-master
Directory         : C:\Kansa-master
IsReadOnly        : False
Exists            : True
FullName          : C:\Kansa-master\testlist9.txt
Extension         : .txt
CreationTime      : 4/27/2016 5:35:51 PM
CreationTimeUtc   : 4/27/2016 10:35:51 PM
LastAccessTime    : 4/27/2016 5:35:51 PM
LastAccessTimeUtc : 4/27/2016 10:35:51 PM
LastWriteTime     : 4/27/2016 5:35:51 PM
LastWriteTimeUtc  : 4/27/2016 10:35:51 PM
Attributes        : Archive

PS C:\Kansa-master> $Targets = Get-Content $TargetList | Foreach-Object { $_.Tri
m() } | Where-Object { $_.Length -gt 0 }
PS C:\Kansa-master> $Targets.Count
109
PS C:\Kansa-master> Write-Output "`$Targets are ${Targets}"
$Targets are asset1 asset2 asset3 asset4 
PS C:\Kansa-master>

>

**Comment by Joseph-Kjar** [comment] 2016-05-10 23:50
I was able to independently reproduce this issue. As mentioned above, the error only appears when using -pushbin and -targetlist together.

**Comment by sc2pyro** [comment] 2016-05-16 18:29
I've developed a workaround that should work for most people. The underlying issue is that the "Send-File" function within Kansa.ps1 only accepts a single string containing a path for the "destination" paramater and only accepts a single session for the "session" parameter. However, when you provide a list of hosts, send-file is invoked with an array of strings being passed to "destination" and an array of objects being passed to "session." This is occurring within the "Get-TargetData" function. 

The modification I made to resolve the issue is within the get-targetdata function:
`# Get our directives both old and new style
        $DirectivesHash  = @{}
        $DirectivesHash = Get-Directives $Module
        if ($Pushbin) {
            $bindep = $($DirectivesHash.Get_Item("BINDEP"))
            if ($bindep) {
                # Push-Bindep -Targets $Targets -Module $Module -Bindep $bindep -Credential $Credential
                $RemoteWindir = Invoke-Command -Session $PSSessions -ScriptBlock { Get-ChildItem -Force env: | Where-Object { $_.Name -match "windir" } | Select-Object -ExpandProperty value }

                # Send-file only supports one destination at a time. Therefore, if we detect more than 
                # one remote directory, we loop through them. This is dependent on the number of remote
                # directories and active remote sessions being the same. 
                if ($RemoteWindir.Count -gt 1){
                    for ($i=0; $i -lt $PSSessions.Count; $i++){
                        $null = Send-File -Path (ls $bindep).FullName -Destination $RemoteWindir[$i] -Session $PSSessions[$i]
                    }
                }
                else{
                    $null = Send-File -Path (ls $bindep).FullName -Destination $RemoteWindir -Session $PSSessions
                }
            }
        }`

As you can see, all I've done is placed send-file in a loop that runs for each session. This method could be thrown off if for some reason there are more sessions created than remote paths found or vice versa. However, this has never been an issue for me during my testing.

**Comment by z4ns4tsu** [comment] 2016-05-19 23:31
Nice @sc2pyro. Thanks for tracking this down. Can you submit a pull request with your patch so we can merge it in while still giving you credit for your work?

**Comment by z4ns4tsu** [comment] 2016-09-11 23:48
@Franky4fngers @rschwass @sc2pyro 

Can you check out the new issue_146 branch and see if the changes I made fix this issue?

**Comment by z4ns4tsu** [comment] 2016-10-06 20:04
Fixed in master.

**Closed by z4ns4tsu** 2016-10-06 20:04 UTC
Labels: bug

**Comment by athegist** [comment] 2016-10-09 02:52
Regression? This used to work fine.
